name: Image Build
on:
  create:
    tags:
      - lambda/v*

jobs:
  go-test:
    name: Go Test
    uses:  tommzn/github-ci/.github/workflows/go.test.v2.yml@v1.0.88
    with:
      work-directory: './lambda'
  go-build:
    name: Go Build
    needs: [go-test]
    uses:  tommzn/github-ci/.github/workflows/go.build.v2.yml@v1.0.90
    with:
      work-directory: './lambda'
  ghcr-image-build:
    name: GHRC Image Build
    needs: [go-build]
    uses:  tommzn/github-ci/.github/workflows/go.ghcr.image.v2.yml@v1.0.91
    with:
      work-directory: './lambda'
    secrets:
        cr-pat: ${{ secrets.CR_PAT }}
  ecr-image-build:
    name: AWS ECR Image Build
    needs: [go-build]
    uses:  tommzn/github-ci/.github/workflows/go.aws.ecr.image.v2.yml@v1.0.92
    with:
      work-directory: './lambda'
      aws-region: eu-central-1
    secrets:
        iam-role: ${{ secrets.IAM_ROLE }}
  
        