name: Image Build
on:
  create:
    tags:
      - lambda/v*

jobs:
  go-test:
    uses:  tommzn/github-ci/.github/workflows/go/go.test.yml@v1.0.84
    inputs:
      working-directory: './lambda'
  go-build:
    needs: [go-test]
    uses:  tommzn/github-ci/.github/workflows/go/go.build.yml@v1.0.84
    inputs:
      working-directory: './lambda'
  image-build:
    name: Build and Deploy Docker Image
    needs: [go-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Golang Binary
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_bin
          path: lambda
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./lambda
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
  
        